// Mocks generated by Mockito 5.0.16 from annotations
// in core/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i10;
import 'dart:convert' as _i29;
import 'dart:typed_data' as _i30;

import 'package:core/data/datasources/db/database_helper.dart' as _i26;
import 'package:core/data/datasources/movie_local_data_source.dart' as _i16;
import 'package:core/data/datasources/movie_remote_data_source.dart' as _i14;
import 'package:core/data/datasources/tv_local_data_source.dart' as _i24;
import 'package:core/data/datasources/tv_remote_data_source.dart' as _i22;
import 'package:core/data/models/movie_models/movie_detail_model.dart' as _i3;
import 'package:core/data/models/movie_models/movie_model.dart' as _i15;
import 'package:core/data/models/movie_models/movie_table.dart' as _i17;
import 'package:core/data/models/tv_models/season_detail_model.dart' as _i5;
import 'package:core/data/models/tv_models/tv_detail_model.dart' as _i4;
import 'package:core/data/models/tv_models/tv_model.dart' as _i23;
import 'package:core/data/models/tv_models/tv_table.dart' as _i25;
import 'package:core/domain/entities/movie_entities/movie.dart' as _i12;
import 'package:core/domain/entities/movie_entities/movie_detail.dart' as _i13;
import 'package:core/domain/entities/tv_entities/season_detail.dart' as _i21;
import 'package:core/domain/entities/tv_entities/tv.dart' as _i19;
import 'package:core/domain/entities/tv_entities/tv_detail.dart' as _i20;
import 'package:core/domain/repositories/movie_repository.dart' as _i9;
import 'package:core/domain/repositories/tv_repository.dart' as _i18;
import 'package:core/utils/failure.dart' as _i11;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/io_client.dart' as _i8;
import 'package:http/src/base_request.dart' as _i31;
import 'package:http/src/client.dart' as _i28;
import 'package:http/src/response.dart' as _i6;
import 'package:http/src/streamed_response.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i27;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieDetailResponse_1 extends _i1.Fake
    implements _i3.MovieDetailResponse {}

class _FakeTvDetailResponse_2 extends _i1.Fake implements _i4.TvDetailResponse {
}

class _FakeSeasonDetailModel_3 extends _i1.Fake
    implements _i5.SeasonDetailModel {}

class _FakeResponse_4 extends _i1.Fake implements _i6.Response {}

class _FakeStreamedResponse_5 extends _i1.Fake implements _i7.StreamedResponse {
}

class _FakeIOStreamedResponse_6 extends _i1.Fake
    implements _i8.IOStreamedResponse {}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i9.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getNowPlayingMovies() => (super.noSuchMethod(
          Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, _i13.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i11.Failure, _i13.MovieDetail>>.value(
              _FakeEither_0<_i11.Failure, _i13.MovieDetail>())) as _i10
          .Future<_i2.Either<_i11.Failure, _i13.MovieDetail>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
          Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> saveWatchlist(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i11.Failure, String>>.value(
                  _FakeEither_0<_i11.Failure, String>()))
          as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> removeWatchlist(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i11.Failure, String>>.value(
                  _FakeEither_0<_i11.Failure, String>()))
          as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i10.Future<bool>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>
      getWatchlistMovies() => (super.noSuchMethod(
          Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>.value(
              _FakeEither_0<_i11.Failure, List<_i12.Movie>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i12.Movie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i14.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i15.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]))
          as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<List<_i15.MovieModel>> getPopularMovies() => (super.noSuchMethod(
          Invocation.method(#getPopularMovies, []),
          returnValue: Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]))
      as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<List<_i15.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
          Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]))
      as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1()))
          as _i10.Future<_i3.MovieDetailResponse>);
  @override
  _i10.Future<List<_i15.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]))
          as _i10.Future<List<_i15.MovieModel>>);
  @override
  _i10.Future<List<_i15.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  Future<List<_i15.MovieModel>>.value(<_i15.MovieModel>[]))
          as _i10.Future<List<_i15.MovieModel>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i16.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> insertMovieWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovieWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i10.Future<String>);
  @override
  _i10.Future<String> removeMovieWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i10.Future<String>);
  @override
  _i10.Future<_i17.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i17.MovieTable?>.value())
          as _i10.Future<_i17.MovieTable?>);
  @override
  _i10.Future<List<_i17.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue:
                  Future<List<_i17.MovieTable>>.value(<_i17.MovieTable>[]))
          as _i10.Future<List<_i17.MovieTable>>);
  @override
  _i10.Future<void> cacheNowPlayingMovies(List<_i17.MovieTable>? movies) =>
      (super.noSuchMethod(Invocation.method(#cacheNowPlayingMovies, [movies]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i10.Future<void>);
  @override
  _i10.Future<List<_i17.MovieTable>> getCachedNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getCachedNowPlayingMovies, []),
              returnValue:
                  Future<List<_i17.MovieTable>>.value(<_i17.MovieTable>[]))
          as _i10.Future<List<_i17.MovieTable>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TVRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRepository extends _i1.Mock implements _i18.TVRepository {
  MockTVRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i19.TV>>> getTVOnTheAir() =>
      (super.noSuchMethod(Invocation.method(#getTVOnTheAir, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i19.TV>>>.value(
              _FakeEither_0<_i11.Failure, List<_i19.TV>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i19.TV>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, _i20.TVDetail>> getTVShowDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTVShowDetail, [id]),
          returnValue: Future<_i2.Either<_i11.Failure, _i20.TVDetail>>.value(
              _FakeEither_0<_i11.Failure, _i20.TVDetail>())) as _i10
          .Future<_i2.Either<_i11.Failure, _i20.TVDetail>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i19.TV>>> getPopularTVShows() =>
      (super.noSuchMethod(Invocation.method(#getPopularTVShows, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i19.TV>>>.value(
              _FakeEither_0<_i11.Failure, List<_i19.TV>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i19.TV>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i19.TV>>> getTopRatedTVShows() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTVShows, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i19.TV>>>.value(
              _FakeEither_0<_i11.Failure, List<_i19.TV>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i19.TV>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i19.TV>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i19.TV>>>.value(
              _FakeEither_0<_i11.Failure, List<_i19.TV>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i19.TV>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i19.TV>>> getSimilarTVShows(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getSimilarTVShows, [id]),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i19.TV>>>.value(
              _FakeEither_0<_i11.Failure, List<_i19.TV>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i19.TV>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i19.TV>>> searchTVShows(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTVShows, [query]),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i19.TV>>>.value(
              _FakeEither_0<_i11.Failure, List<_i19.TV>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i19.TV>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> saveWatchlist(
          _i20.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tv]),
              returnValue: Future<_i2.Either<_i11.Failure, String>>.value(
                  _FakeEither_0<_i11.Failure, String>()))
          as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, String>> removeWatchlist(
          _i20.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tv]),
              returnValue: Future<_i2.Either<_i11.Failure, String>>.value(
                  _FakeEither_0<_i11.Failure, String>()))
          as _i10.Future<_i2.Either<_i11.Failure, String>>);
  @override
  _i10.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i10.Future<bool>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, List<_i19.TV>>> getWatchListTVShow() =>
      (super.noSuchMethod(Invocation.method(#getWatchListTVShow, []),
          returnValue: Future<_i2.Either<_i11.Failure, List<_i19.TV>>>.value(
              _FakeEither_0<_i11.Failure, List<_i19.TV>>())) as _i10
          .Future<_i2.Either<_i11.Failure, List<_i19.TV>>>);
  @override
  _i10.Future<_i2.Either<_i11.Failure, _i21.SeasonDetail>> getTVSeasonDetail(
          int? tvId, int? season) =>
      (super.noSuchMethod(Invocation.method(#getTVSeasonDetail, [tvId, season]),
              returnValue:
                  Future<_i2.Either<_i11.Failure, _i21.SeasonDetail>>.value(
                      _FakeEither_0<_i11.Failure, _i21.SeasonDetail>()))
          as _i10.Future<_i2.Either<_i11.Failure, _i21.SeasonDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TVRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRemoteDataSource extends _i1.Mock
    implements _i22.TVRemoteDataSource {
  MockTVRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i23.TVModel>> getTVOnTheAir() =>
      (super.noSuchMethod(Invocation.method(#getTVOnTheAir, []),
              returnValue: Future<List<_i23.TVModel>>.value(<_i23.TVModel>[]))
          as _i10.Future<List<_i23.TVModel>>);
  @override
  _i10.Future<_i4.TvDetailResponse> getTVDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTVDetail, [id]),
              returnValue:
                  Future<_i4.TvDetailResponse>.value(_FakeTvDetailResponse_2()))
          as _i10.Future<_i4.TvDetailResponse>);
  @override
  _i10.Future<List<_i23.TVModel>> getPopularTVShows() =>
      (super.noSuchMethod(Invocation.method(#getPopularTVShows, []),
              returnValue: Future<List<_i23.TVModel>>.value(<_i23.TVModel>[]))
          as _i10.Future<List<_i23.TVModel>>);
  @override
  _i10.Future<List<_i23.TVModel>> getTopRatedTVShows() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTVShows, []),
              returnValue: Future<List<_i23.TVModel>>.value(<_i23.TVModel>[]))
          as _i10.Future<List<_i23.TVModel>>);
  @override
  _i10.Future<List<_i23.TVModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue: Future<List<_i23.TVModel>>.value(<_i23.TVModel>[]))
          as _i10.Future<List<_i23.TVModel>>);
  @override
  _i10.Future<List<_i23.TVModel>> getSimilarTVShows(int? id) =>
      (super.noSuchMethod(Invocation.method(#getSimilarTVShows, [id]),
              returnValue: Future<List<_i23.TVModel>>.value(<_i23.TVModel>[]))
          as _i10.Future<List<_i23.TVModel>>);
  @override
  _i10.Future<List<_i23.TVModel>> searchTVShows(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTVShows, [query]),
              returnValue: Future<List<_i23.TVModel>>.value(<_i23.TVModel>[]))
          as _i10.Future<List<_i23.TVModel>>);
  @override
  _i10.Future<_i5.SeasonDetailModel> getSeasonDetail(int? tvId, int? season) =>
      (super.noSuchMethod(Invocation.method(#getSeasonDetail, [tvId, season]),
              returnValue: Future<_i5.SeasonDetailModel>.value(
                  _FakeSeasonDetailModel_3()))
          as _i10.Future<_i5.SeasonDetailModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TVLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVLocalDataSource extends _i1.Mock implements _i24.TVLocalDataSource {
  MockTVLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> insertTVWatchlist(_i25.TVTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertTVWatchlist, [tv]),
          returnValue: Future<String>.value('')) as _i10.Future<String>);
  @override
  _i10.Future<String> removeTVWatchlist(_i25.TVTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeTVWatchlist, [tv]),
          returnValue: Future<String>.value('')) as _i10.Future<String>);
  @override
  _i10.Future<_i25.TVTable?> getTVShowById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTVShowById, [id]),
              returnValue: Future<_i25.TVTable?>.value())
          as _i10.Future<_i25.TVTable?>);
  @override
  _i10.Future<List<_i25.TVTable>> getWatchlistTVShow() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTVShow, []),
              returnValue: Future<List<_i25.TVTable>>.value(<_i25.TVTable>[]))
          as _i10.Future<List<_i25.TVTable>>);
  @override
  _i10.Future<void> cacheTVOnTheAir(List<_i25.TVTable>? tv) =>
      (super.noSuchMethod(Invocation.method(#cacheTVOnTheAir, [tv]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i10.Future<void>);
  @override
  _i10.Future<List<_i25.TVTable>> getCachedTVOnTheAir() =>
      (super.noSuchMethod(Invocation.method(#getCachedTVOnTheAir, []),
              returnValue: Future<List<_i25.TVTable>>.value(<_i25.TVTable>[]))
          as _i10.Future<List<_i25.TVTable>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i26.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i27.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i27.Database?>.value())
          as _i10.Future<_i27.Database?>);
  @override
  _i10.Future<void> insertMoviesCacheTransaction(
          List<_i17.MovieTable>? movies, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertMoviesCacheTransaction, [movies, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i10.Future<void>);
  @override
  _i10.Future<List<Map<String, dynamic>>> getMoviesCacheMovies(
          String? category) =>
      (super.noSuchMethod(Invocation.method(#getMoviesCacheMovies, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i10.Future<List<Map<String, dynamic>>>);
  @override
  _i10.Future<int> clearMoviesCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearMoviesCache, [category]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<int> insertMovieWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovieWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<int> removeMovieWatchlist(_i17.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeMovieWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i10.Future<Map<String, dynamic>?>);
  @override
  _i10.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i10.Future<List<Map<String, dynamic>>>);
  @override
  _i10.Future<int> insertTVWatchlist(_i25.TVTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertTVWatchlist, [tv]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<int> removeTVWatchlist(_i25.TVTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeTVWatchlist, [tv]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  _i10.Future<Map<String, dynamic>?> getTVShowById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTVShowById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i10.Future<Map<String, dynamic>?>);
  @override
  _i10.Future<List<Map<String, dynamic>>> getWatchlistTVShow() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTVShow, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i10.Future<List<Map<String, dynamic>>>);
  @override
  _i10.Future<void> insertTVCacheTransaction(
          List<_i25.TVTable>? movies, String? category) =>
      (super.noSuchMethod(
              Invocation.method(#insertTVCacheTransaction, [movies, category]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i10.Future<void>);
  @override
  _i10.Future<List<Map<String, dynamic>>> getTVCacheMovies(String? category) =>
      (super.noSuchMethod(Invocation.method(#getTVCacheMovies, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i10.Future<List<Map<String, dynamic>>>);
  @override
  _i10.Future<int> clearTVCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearTVCache, [category]),
          returnValue: Future<int>.value(0)) as _i10.Future<int>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i28.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i10.Future<String>);
  @override
  _i10.Future<_i30.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i30.Uint8List>.value(_i30.Uint8List(0)))
          as _i10.Future<_i30.Uint8List>);
  @override
  _i10.Future<_i7.StreamedResponse> send(_i31.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i7.StreamedResponse>.value(_FakeStreamedResponse_5()))
          as _i10.Future<_i7.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [IOClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOClient extends _i1.Mock implements _i8.IOClient {
  MockIOClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i8.IOStreamedResponse> send(_i31.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: Future<_i8.IOStreamedResponse>.value(
                  _FakeIOStreamedResponse_6()))
          as _i10.Future<_i8.IOStreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  _i10.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i29.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i10.Future<_i6.Response>);
  @override
  _i10.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i10.Future<String>);
  @override
  _i10.Future<_i30.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i30.Uint8List>.value(_i30.Uint8List(0)))
          as _i10.Future<_i30.Uint8List>);
  @override
  String toString() => super.toString();
}
